name: Build and deploy movebank dispatcher
on:
  push:
    branches:
      - main
      - 'release-**'

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v3
      - id: vars
        run: |
          echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi/movebank-dispatcher" >> $GITHUB_OUTPUT

  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v1-stable
    needs: vars
    with:
      environment: dev
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}

  deploy_dev:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v1-stable
    if: startsWith(github.ref, 'refs/heads/main')
    needs: [vars, build]
    with:
      environment: dev
      chart_name: movebank-dispatcher
      chart_version: '0.1.0'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}

  deploy_stage:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v1-stable
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build]
    with:
      environment: stage
      chart_name: movebank-dispatcher
      chart_version: '0.1.0'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}

  deploy_prod:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v1-stable
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build, deploy_stage]
    with:
      environment: prod
      chart_name: movebank-dispatcher
      chart_version: '0.1.0'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}