name: Build and deploy movebank dispatcher
on:
  push:
    branches:
      - main
      - 'release-**'
      - 'gundi-3070'

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi/movebank-dispatcher" >> $GITHUB_OUTPUT

  run_unit_tests:
      runs-on: ubuntu-latest
      needs: [vars]
      steps:
        - name: Checkout branch
          uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.8' 
        - name: Install pip
          run: python -m ensurepip --upgrade
        - name: Install dependencies
          run: pip install -r requirements.in
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Run unit tests
          run: pytest -s
          env:
            MOVEBANK_PASSWORD: test
            MOVEBANK_USERNAME: test
            TRANSFORMED_OBSERVATIONS_SUB_ID: test
            TRACING_ENABLED: False

  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v2
    needs: [run_unit_tests,vars]
    with:
      environment: stage
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}

  deploy_dev:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/main')
    needs: [vars, build]
    with:
      environment: dev
      chart_name: movebank-dispatcher
      chart_version: '0.1.0'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit

  deploy_stage:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build]
    with:
      environment: stage
      chart_name: movebank-dispatcher
      chart_version: '0.1.0'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit

  deploy_prod:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build, deploy_stage]
    with:
      environment: prod
      chart_name: movebank-dispatcher
      chart_version: '0.1.0'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit